Repository Bash-it/bash-it, pull requests merged in 2025-04, with the labels that each got.

#1954 Themes: Fix `shellcheck` (SC2154); Part C
  themes/barbuk/barbuk.theme.bash
  themes/binaryanomaly/binaryanomaly.theme.bash
  themes/modern/modern.theme.bash
Labels: waiting-for-response

#1831 aliases: Add new git-omz alias file
  aliases/available/git-omz.aliases.bash
  aliases/available/git.aliases.bash
  test/lib/search.bats
  vendor/github.com/ohmyzsh/ohmyzsh/LICENSE.txt
  vendor/github.com/ohmyzsh/ohmyzsh/plugins/git/README.md
  vendor/github.com/ohmyzsh/ohmyzsh/plugins/git/git.plugin.zsh
Labels: seems abandoned, waiting-for-response

#2060 Add virtualenv prompt for robbyrussell theme
  themes/base.theme.bash
  themes/robbyrussell/robbyrussell.theme.bash
Labels: seems abandoned

#2065 lib/helpers: remove log message from `_command_exists()` et al
  lib/helpers.bash
  lib/utilities.bash
  test/lib/helpers.bats
  test/lib/utilities.bats
Labels: clean up, seems abandoned, waiting-for-response
